programan:
    workspace:
        path: /Users/apple/Workspace/community_workspace

spring:
    datasource:
            url: jdbc:mysql://101.132.112.87:3306/community?characterEncoding=utf8&autoReconnect=true&useSSL=false
            username: programan
            password: acm666666
            driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
        hibernate:
            ddl-auto: none
        show-sql: false
        open-in-view: false
        database: mysql
    thymeleaf:
        prefix: classpath:/static/
    servlet:
          multipart:
              enabled: true
              max-file-size: 400MB
              max-request-size: 400MB
              fileSizeThreshold: 10MB
    redis:
            database: 1
            host: 101.132.112.87
            port: 6379
            password: acm666666
            jedis:
                pool:
                    max-active: 8
                    min-idle: 0
                    max-idle: 8
                    max-wait: -1ms
            timeout: 2000ms