spring:
    datasource:
            url: jdbc:mysql://101.132.112.87:3306/hotel_manage?characterEncoding=utf8&autoReconnect=true&useSSL=false
            username: programan
            password: acm666666
            driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
        hibernate:
            ddl-auto: none
        show-sql: false
        open-in-view: false
        database: mysql
    thymeleaf:
        prefix: classpath:/static/